name: bonusvarsel
description: Bonusvarsel – SAS EuroBonus companion app
publish_to: "none"

version: 1.2.0+31

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  intl: ^0.19.0
  http: ^1.2.2
  in_app_purchase: ^3.2.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_markdown: ^0.7.7+1
  cloud_functions: ^5.6.2
  in_app_purchase_storekit: ^0.4.8+1
  firebase_messaging: ^15.2.10
  app_links: ^7.0.0
  webview_flutter: ^4.13.1
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/travel/
    - assets/brands/

    - assets/images/travel/

    - assets/eb.shopping.min.json
    - assets/eb.shopping.pretty.json
    - assets/mam.offers.json
    - assets/mam.offers.min.json
    - assets/offers.json
