-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWo63qgafk/0ztpbK
CVKJWI3uxTXkzkfMnIH5h08pSemgCgYIKoZIzj0DAQehRANCAAR50jEBkLLwr3Gk
aZpLsB6GIpkzcKxBnwwyyI+t+FOZ7xDHrnvdmhrz+rgZfeSV/kf7bazoXe0OjpBz
dyTYrdL1
-----END PRIVATE KEY-----