#!/usr/bin/env python3
import os

path = os.path.expanduser('~/bonusvarsel/lib/pages/cards_page.dart')

with open(path, 'r') as f:
    original = f.read()
with open(path + '.bak2', 'w') as f:
    f.write(original)

# Skriv filen linje for linje for å unngå escape-problemer
lines = []
lines.append("import 'package:flutter/material.dart';")
lines.append("import 'package:url_launcher/url_launcher.dart';")
lines.append("import 'package:firebase_auth/firebase_auth.dart';")
lines.append("import '../pages/login_page.dart';")
lines.append("import '../models/card_catalog.dart';")
lines.append("import '../services/user_state.dart';")
lines.append("")
lines.append("class CardsPage extends StatefulWidget {")
lines.append("  const CardsPage({super.key});")
lines.append("  @override")
lines.append("  State<CardsPage> createState() => _CardsPageState();")
lines.append("}")
lines.append("")
lines.append("class _CardsPageState extends State<CardsPage> {")
lines.append("  String? _selectedCardId;")
lines.append("")
lines.append("  static const _cards = [")
lines.append("    _CardInfo(")
lines.append("      id: 'sas_amex',")
lines.append("      name: 'SAS EuroBonus American Express',")
lines.append("      network: 'Amex',")
lines.append("      ratePer100: 20,")
lines.append("      accentColor: Color(0xFF1e40af),")
lines.append("      bgColor: Color(0xFFEFF6FF),")
lines.append("      borderColor: Color(0xFF93C5FD),")
lines.append("      description: 'Beste SAS-kort. 20 poeng per 100 kr på alle kjøp. Søk direkte hos American Express Norge.',")
lines.append("      url: 'https://www.americanexpress.com/no/',")
lines.append("      badge: 'Mest poeng',")
lines.append("      emoji: '✈️',")
lines.append("    ),")
lines.append("    _CardInfo(")
lines.append("      id: 'sas_mc',")
lines.append("      name: 'SAS EuroBonus Mastercard',")
lines.append("      network: 'Mastercard',")
lines.append("      ratePer100: 15,")
lines.append("      accentColor: Color(0xFF1e40af),")
lines.append("      bgColor: Color(0xFFEFF6FF),")
lines.append("      borderColor: Color(0xFF93C5FD),")
lines.append("      description: 'SAS EuroBonus Mastercard via DNB. Gå til Mine kort i DNB-appen → Mastercard → Oppgrader → legg inn EuroBonus-nummer.',")
lines.append("      url: 'https://saseurobonusmastercard.no/kortene/mastercard/',")
lines.append("      badge: 'Populær',")
lines.append("      emoji: '🔵',")
lines.append("    ),")
lines.append("    _CardInfo(")
lines.append("      id: 'sas_visa',")
lines.append("      name: 'SAS EuroBonus Visa',")
lines.append("      network: 'Visa',")
lines.append("      ratePer100: 10,")
lines.append("      accentColor: Color(0xFF1e40af),")
lines.append("      bgColor: Color(0xFFEFF6FF),")
lines.append("      borderColor: Color(0xFF93C5FD),")
lines.append("      description: 'SAS EuroBonus Visa via Lunar. Last ned Lunar-appen og søk om SAS EuroBonus Visa direkte der.',")
lines.append("      url: 'https://www.lunar.app/en/personal/sas-eurobonus',")
lines.append("      badge: null,")
lines.append("      emoji: '💳',")
lines.append("    ),")
lines.append("    _CardInfo(")
lines.append("      id: 'trumf_visa',")
lines.append("      name: 'Trumf Visa',")
lines.append("      network: 'Visa',")
lines.append("      ratePer100: 10,")
lines.append("      accentColor: Color(0xFF15803D),")
lines.append("      bgColor: Color(0xFFECFDF5),")
lines.append("      borderColor: Color(0xFF86EFAC),")
lines.append("      description: 'Trumf Visa via Trumf Pay. Legg til Visa-kortet ditt i Trumf-appen under Trumf Pay for å koble opptjening.',")
lines.append("      url: 'https://www.trumf.no/trumf-kredittkort/trumf-kredittkort-i-trumf-pay',")
lines.append("      badge: 'Trumf',")
lines.append("      emoji: '🟢',")
lines.append("    ),")
lines.append("    _CardInfo(")
lines.append("      id: 'trumf_mc',")
lines.append("      name: 'Trumf Mastercard',")
lines.append("      network: 'Mastercard',")
lines.append("      ratePer100: 8,")
lines.append("      accentColor: Color(0xFF15803D),")
lines.append("      bgColor: Color(0xFFECFDF5),")
lines.append("      borderColor: Color(0xFF86EFAC),")
lines.append("      description: 'Trumf sitt eget Mastercard. Søk på trumf.no. 8 poeng per 100 kr på alle kjøp.',")
lines.append("      url: 'https://www.trumf.no',")
lines.append("      badge: null,")
lines.append("      emoji: '🌿',")
lines.append("    ),")
lines.append("  ];")
lines.append("")
lines.append("  @override")
lines.append("  void initState() {")
lines.append("    super.initState();")
lines.append("    _loadSelected();")
lines.append("  }")
lines.append("")
lines.append("  Future<void> _loadSelected() async {")
lines.append("    final id = await UserState.getSelectedCardId();")
lines.append("    if (!mounted) return;")
lines.append("    setState(() => _selectedCardId = id);")
lines.append("  }")
lines.append("")
lines.append("  Future<void> _selectCard(String id, int rate) async {")
lines.append("    final user = FirebaseAuth.instance.currentUser;")
lines.append("    if (user == null) {")
lines.append("      if (!mounted) return;")
lines.append("      await Navigator.of(context).push(")
lines.append("        MaterialPageRoute(")
lines.append("          builder: (_) => LoginPage(")
lines.append("            onSuccess: () async {")
lines.append("              await UserState.setSelectedCard(id, rate.toDouble());")
lines.append("              if (!mounted) return;")
lines.append("              setState(() => _selectedCardId = id);")
lines.append("            },")
lines.append("          ),")
lines.append("        ),")
lines.append("      );")
lines.append("      return;")
lines.append("    }")
lines.append("    await UserState.setSelectedCard(id, rate.toDouble());")
lines.append("    if (!mounted) return;")
lines.append("    setState(() => _selectedCardId = id);")
lines.append("    ScaffoldMessenger.of(context).showSnackBar(")
lines.append("      SnackBar(")
lines.append("        content: Text(CardCatalog.nameFor(id) + ' valgt som aktivt kort'),")
lines.append("        duration: const Duration(seconds: 2),")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  Future<void> _openUrl(String url) async {")
lines.append("    final uri = Uri.parse(url);")
lines.append("    if (!await launchUrl(uri, mode: LaunchMode.externalApplication)) {")
lines.append("      if (!mounted) return;")
lines.append("      ScaffoldMessenger.of(context).showSnackBar(")
lines.append("        const SnackBar(content: Text('Kunne ikke åpne lenken')),")
lines.append("      );")
lines.append("    }")
lines.append("  }")
lines.append("")
lines.append("  @override")
lines.append("  Widget build(BuildContext context) {")
lines.append("    final selected = _cards.where((c) => c.id == _selectedCardId).firstOrNull;")
lines.append("")
lines.append("    return Scaffold(")
lines.append("      backgroundColor: const Color(0xFFF1F5F9),")
lines.append("      appBar: AppBar(")
lines.append("        backgroundColor: Colors.white,")
lines.append("        elevation: 0,")
lines.append("        title: const Text(")
lines.append("          'Kort',")
lines.append("          style: TextStyle(color: Colors.black87, fontWeight: FontWeight.w900, fontSize: 20),")
lines.append("        ),")
lines.append("        bottom: PreferredSize(")
lines.append("          preferredSize: const Size.fromHeight(1),")
lines.append("          child: Container(color: const Color(0xFFE2E8F0), height: 1),")
lines.append("        ),")
lines.append("      ),")
lines.append("      body: ListView(")
lines.append("        padding: const EdgeInsets.all(16),")
lines.append("        children: [")
lines.append("          // Hero")
lines.append("          Container(")
lines.append("            padding: const EdgeInsets.all(16),")
lines.append("            decoration: BoxDecoration(")
lines.append("              gradient: const LinearGradient(")
lines.append("                colors: [Color(0xFF1e40af), Color(0xFF1D4ED8)],")
lines.append("                begin: Alignment.topLeft,")
lines.append("                end: Alignment.bottomRight,")
lines.append("              ),")
lines.append("              borderRadius: BorderRadius.circular(18),")
lines.append("              boxShadow: [BoxShadow(color: Color(0x331e40af), blurRadius: 10, offset: Offset(0, 4))],")
lines.append("            ),")
lines.append("            child: Row(")
lines.append("              children: [")
lines.append("                Container(")
lines.append("                  padding: const EdgeInsets.all(10),")
lines.append("                  decoration: BoxDecoration(")
lines.append("                    color: Colors.white24,")
lines.append("                    borderRadius: BorderRadius.circular(12),")
lines.append("                  ),")
lines.append("                  child: const Icon(Icons.credit_card_rounded, color: Colors.white, size: 26),")
lines.append("                ),")
lines.append("                const SizedBox(width: 14),")
lines.append("                Expanded(")
lines.append("                  child: Column(")
lines.append("                    crossAxisAlignment: CrossAxisAlignment.start,")
lines.append("                    children: [")
lines.append("                      const Text('Velg bonuskort',")
lines.append("                        style: TextStyle(color: Colors.white, fontSize: 17, fontWeight: FontWeight.w900)),")
lines.append("                      const SizedBox(height: 3),")
lines.append("                      Text(")
lines.append("                        selected != null ? 'Aktivt: ${selected.name}' : 'Ingen kort valgt ennå',")
lines.append("                        style: const TextStyle(color: Colors.white70, fontSize: 13),")
lines.append("                      ),")
lines.append("                    ],")
lines.append("                  ),")
lines.append("                ),")
lines.append("                if (selected != null)")
lines.append("                  const Icon(Icons.check_circle_rounded, color: Colors.white, size: 24),")
lines.append("              ],")
lines.append("            ),")
lines.append("          ),")
lines.append("          const SizedBox(height: 20),")
lines.append("")
lines.append("          // SAS-seksjon")
lines.append("          _sectionHeader('✈️  SAS EuroBonus', const Color(0xFF1e40af)),")
lines.append("          const SizedBox(height: 8),")
lines.append("          ..._cards.where((c) => c.id.startsWith('sas')).map((card) => _CardTile(")
lines.append("            card: card,")
lines.append("            isSelected: _selectedCardId == card.id,")
lines.append("            onSelect: () => _selectCard(card.id, card.ratePer100),")
lines.append("            onOpenUrl: () => _openUrl(card.url),")
lines.append("          )),")
lines.append("          const SizedBox(height: 8),")
lines.append("")
lines.append("          // Trumf-seksjon")
lines.append("          _sectionHeader('🟢  Trumf', const Color(0xFF15803D)),")
lines.append("          const SizedBox(height: 8),")
lines.append("          ..._cards.where((c) => c.id.startsWith('trumf')).map((card) => _CardTile(")
lines.append("            card: card,")
lines.append("            isSelected: _selectedCardId == card.id,")
lines.append("            onSelect: () => _selectCard(card.id, card.ratePer100),")
lines.append("            onOpenUrl: () => _openUrl(card.url),")
lines.append("          )),")
lines.append("          const SizedBox(height: 12),")
lines.append("")
lines.append("          // Info-boks")
lines.append("          Container(")
lines.append("            padding: const EdgeInsets.all(14),")
lines.append("            decoration: BoxDecoration(")
lines.append("              color: Colors.white,")
lines.append("              borderRadius: BorderRadius.circular(14),")
lines.append("              border: Border.all(color: const Color(0xFFE2E8F0)),")
lines.append("            ),")
lines.append("            child: const Column(")
lines.append("              crossAxisAlignment: CrossAxisAlignment.start,")
lines.append("              children: [")
lines.append("                Text('ℹ️  Slik fungerer kortvalget',")
lines.append("                  style: TextStyle(color: Colors.black87, fontWeight: FontWeight.w900, fontSize: 14)),")
lines.append("                SizedBox(height: 8),")
lines.append("                Text(")
lines.append("                  '• Valgt kort brukes til poengberegning på Reise-siden\\n'")
lines.append("                  '• Poeng per 100 kr er basert på standard opptjeningsrate\\n'")
lines.append("                  '• Faktisk opptjening avhenger av butikk og tilbud\\n'")
lines.append("                  '• Trykk \"Se kort\" for å søke om eller lese mer',")
lines.append("                  style: TextStyle(color: Colors.black54, height: 1.55, fontSize: 13),")
lines.append("                ),")
lines.append("              ],")
lines.append("            ),")
lines.append("          ),")
lines.append("          const SizedBox(height: 24),")
lines.append("        ],")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  Widget _sectionHeader(String label, Color color) {")
lines.append("    return Row(children: [")
lines.append("      Text(label, style: TextStyle(color: color, fontWeight: FontWeight.w900, fontSize: 15)),")
lines.append("      const SizedBox(width: 8),")
lines.append("      Expanded(child: Divider(color: color.withValues(alpha: 0.25))),")
lines.append("    ]);")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("class _CardTile extends StatelessWidget {")
lines.append("  final _CardInfo card;")
lines.append("  final bool isSelected;")
lines.append("  final VoidCallback onSelect;")
lines.append("  final VoidCallback onOpenUrl;")
lines.append("")
lines.append("  const _CardTile({")
lines.append("    required this.card,")
lines.append("    required this.isSelected,")
lines.append("    required this.onSelect,")
lines.append("    required this.onOpenUrl,")
lines.append("  });")
lines.append("")
lines.append("  @override")
lines.append("  Widget build(BuildContext context) {")
lines.append("    return Container(")
lines.append("      margin: const EdgeInsets.only(bottom: 10),")
lines.append("      decoration: BoxDecoration(")
lines.append("        color: isSelected ? card.bgColor : Colors.white,")
lines.append("        borderRadius: BorderRadius.circular(16),")
lines.append("        border: Border.all(")
lines.append("          color: isSelected ? card.accentColor : const Color(0xFFE2E8F0),")
lines.append("          width: isSelected ? 2 : 1,")
lines.append("        ),")
lines.append("        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.04), blurRadius: 6, offset: Offset(0, 2))],")
lines.append("      ),")
lines.append("      child: InkWell(")
lines.append("        borderRadius: BorderRadius.circular(16),")
lines.append("        onTap: onSelect,")
lines.append("        child: Padding(")
lines.append("          padding: const EdgeInsets.all(14),")
lines.append("          child: Column(")
lines.append("            crossAxisAlignment: CrossAxisAlignment.start,")
lines.append("            children: [")
lines.append("              Row(children: [")
lines.append("                Container(")
lines.append("                  width: 44, height: 44,")
lines.append("                  decoration: BoxDecoration(")
lines.append("                    color: card.bgColor,")
lines.append("                    borderRadius: BorderRadius.circular(12),")
lines.append("                    border: Border.all(color: card.borderColor),")
lines.append("                  ),")
lines.append("                  child: Center(child: Text(card.emoji, style: const TextStyle(fontSize: 22))),")
lines.append("                ),")
lines.append("                const SizedBox(width: 12),")
lines.append("                Expanded(")
lines.append("                  child: Column(")
lines.append("                    crossAxisAlignment: CrossAxisAlignment.start,")
lines.append("                    children: [")
lines.append("                      Row(children: [")
lines.append("                        Expanded(child: Text(card.name,")
lines.append("                          style: const TextStyle(color: Colors.black87, fontWeight: FontWeight.w900, fontSize: 14))),")
lines.append("                        if (card.badge != null)")
lines.append("                          Container(")
lines.append("                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),")
lines.append("                            decoration: BoxDecoration(")
lines.append("                              color: card.bgColor,")
lines.append("                              borderRadius: BorderRadius.circular(999),")
lines.append("                              border: Border.all(color: card.borderColor),")
lines.append("                            ),")
lines.append("                            child: Text(card.badge!,")
lines.append("                              style: TextStyle(color: card.accentColor, fontWeight: FontWeight.w800, fontSize: 11)),")
lines.append("                          ),")
lines.append("                      ]),")
lines.append("                      const SizedBox(height: 3),")
# Nøkkellinje - bruker list append for å unngå escape-problemer i Python
lines.append('                      Text(')
lines.append("                        '${card.network}  \u2022  ${card.ratePer100} poeng/100 kr',")
lines.append('                        style: TextStyle(color: card.accentColor, fontSize: 12, fontWeight: FontWeight.w700),')
lines.append('                      ),')
lines.append("                    ],")
lines.append("                  ),")
lines.append("                ),")
lines.append("                const SizedBox(width: 8),")
lines.append("                Icon(")
lines.append("                  isSelected ? Icons.check_circle_rounded : Icons.radio_button_off_rounded,")
lines.append("                  color: isSelected ? card.accentColor : Colors.black26, size: 22,")
lines.append("                ),")
lines.append("              ]),")
lines.append("              const SizedBox(height: 10),")
lines.append("              Text(card.description,")
lines.append("                style: const TextStyle(color: Colors.black54, fontSize: 13, height: 1.4)),")
lines.append("              const SizedBox(height: 12),")
lines.append("              Row(children: [")
lines.append("                Expanded(")
lines.append("                  child: FilledButton(")
lines.append("                    style: FilledButton.styleFrom(")
lines.append("                      backgroundColor: isSelected ? card.accentColor : const Color(0xFFF1F5F9),")
lines.append("                      foregroundColor: isSelected ? Colors.white : Colors.black87,")
lines.append("                      padding: const EdgeInsets.symmetric(vertical: 10),")
lines.append("                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),")
lines.append("                      elevation: 0,")
lines.append("                    ),")
lines.append("                    onPressed: onSelect,")
lines.append("                    child: Text(isSelected ? '\u2713 Aktivt kort' : 'Velg dette kortet',")
lines.append("                      style: const TextStyle(fontWeight: FontWeight.w900)),")
lines.append("                  ),")
lines.append("                ),")
lines.append("                const SizedBox(width: 10),")
lines.append("                OutlinedButton(")
lines.append("                  style: OutlinedButton.styleFrom(")
lines.append("                    foregroundColor: card.accentColor,")
lines.append("                    side: BorderSide(color: card.borderColor, width: 1.5),")
lines.append("                    padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 14),")
lines.append("                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),")
lines.append("                  ),")
lines.append("                  onPressed: onOpenUrl,")
lines.append("                  child: const Text('Se kort', style: TextStyle(fontWeight: FontWeight.w700)),")
lines.append("                ),")
lines.append("              ]),")
lines.append("            ],")
lines.append("          ),")
lines.append("        ),")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("}")
lines.append("")
lines.append("class _CardInfo {")
lines.append("  final String id;")
lines.append("  final String name;")
lines.append("  final String network;")
lines.append("  final int ratePer100;")
lines.append("  final Color accentColor;")
lines.append("  final Color bgColor;")
lines.append("  final Color borderColor;")
lines.append("  final String description;")
lines.append("  final String url;")
lines.append("  final String? badge;")
lines.append("  final String emoji;")
lines.append("")
lines.append("  const _CardInfo({")
lines.append("    required this.id,")
lines.append("    required this.name,")
lines.append("    required this.network,")
lines.append("    required this.ratePer100,")
lines.append("    required this.accentColor,")
lines.append("    required this.bgColor,")
lines.append("    required this.borderColor,")
lines.append("    required this.description,")
lines.append("    required this.url,")
lines.append("    this.badge,")
lines.append("    required this.emoji,")
lines.append("  });")
lines.append("}")

dart = '\n'.join(lines)

with open(path, 'w') as f:
    f.write(dart)

# Verifiser at interpolation er riktig
import subprocess
result = subprocess.run(['grep', 'card.network', path], capture_output=True, text=True)
print("Interpolation-sjekk:", result.stdout.strip())

print("✅ cards_page.dart skrevet om (v2)")
print("   Fikset: ${card.network} og ${card.ratePer100} interpolation")
print("   Endret: Blå hero-banner øverst (ikke hvit)")
print("   Bakgrunn: Color(0xFFF1F5F9) – lys grå i stedet for ren hvit")
